[
      {
        typeId: 'New',
        quoteRefNo: 'QR0123456789',
        policyNo: 'P0123456789',
        status: 'new',
        insuredName: 'Sodales ac',
        brokerage: 'Chubb Broker',
        productId: 'Flexiguard',
        producer: 'Chubb Broker',
        policyPeriod: '10-Oct-21 - 09-Oct-22',
        transactionEffectiveDate: '10-Oct-21',
        premium: '1500000',
        currency: 'SGD',
        lastUpdated: '10-Oct-21',
        actions: []
      },
      {
        typeId: 'New',
        quoteRefNo: 'QR0123456789',
        policyNo: 'P0123456789',
        status: 'in-progress',
        insuredName: 'Sodales ac',
        brokerage: 'Chubb Broker',
        productId: 'Flexiguard',
        producer: 'Chubb Broker',
        policyPeriod: '10-Oct-21 - 09-Oct-22',
        transactionEffectiveDate: '10-Oct-21',
        premium: '1500000',
        currency: 'SGD',
        lastUpdated: '10-Oct-21',
        actions: []
      },
      {
        typeId: 'New',
        quoteRefNo: 'QR0123456789',
        policyNo: 'P0123456789',
        status: 'in-progress',
        insuredName: 'Sodales ac',
        brokerage: 'Chubb Broker',
        productId: 'Flexiguard',
        producer: 'Chubb Broker',
        policyPeriod: '10-Oct-21 - 09-Oct-22',
        transactionEffectiveDate: '10-Oct-21',
        premium: '1500000',
        currency: 'SGD',
        lastUpdated: '10-Oct-21',
        actions: []
      },
      {
        typeId: 'New',
        quoteRefNo: 'QR0123456789',
        policyNo: 'P0123456789',
        status: 'unsuccessful',
        insuredName: 'Sodales ac',
        brokerage: 'Chubb Broker',
        productId: 'Flexiguard',
        producer: 'Chubb Broker',
        policyPeriod: '10-Oct-21 - 09-Oct-22',
        transactionEffectiveDate: '10-Oct-21',
        premium: '1500000',
        currency: 'SGD',
        lastUpdated: '10-Oct-21',
        actions: []
      },
      {
        typeId: 'New',
        quoteRefNo: 'QR0123456789',
        policyNo: 'P0123456789',
        status: 'under-review',
        insuredName: 'Sodales ac',
        brokerage: 'Chubb Broker',
        productId: 'Flexiguard',
        producer: 'Chubb Broker',
        policyPeriod: '10-Oct-21 - 09-Oct-22',
        transactionEffectiveDate: '10-Oct-21',
        premium: '1500000',
        currency: 'SGD',
        lastUpdated: '10-Oct-21',
        actions: []
      },
      {
        typeId: 'New',
        quoteRefNo: 'QR0123456789',
        policyNo: 'P0123456789',
        status: 'referral-pending-info',
        insuredName: 'Sodales ac',
        brokerage: 'Chubb Broker',
        productId: 'Flexiguard',
        producer: 'Chubb Broker',
        policyPeriod: '10-Oct-21 - 09-Oct-22',
        transactionEffectiveDate: '10-Oct-21',
        premium: '1500000',
        currency: 'SGD',
        lastUpdated: '10-Oct-21',
        actions: []
      },
    ]

    quotes listing

    [
      {
        typeId: 'New',
        quoteRefNo: 'QR0123456789',
        policyNo: 'P0123456789',
        status: 'new',
        insuredName: 'Sodales ac',
        brokerage: 'Chubb Broker',
        productId: 'Flexiguard',
        producer: 'Chubb Broker',
        policyPeriod: '10-Oct-21 - 09-Oct-22',
        transactionEffectiveDate: '10-Oct-21',
        premium: '1500000',
        currency: 'SGD',
        lastUpdated: '10-Oct-21',
        actions: []
      },
      {
        typeId: 'New',
        quoteRefNo: 'QR0123456789',
        policyNo: 'P0123456789',
        status: 'in-progress',
        insuredName: 'Sodales ac',
        brokerage: 'Chubb Broker',
        productId: 'Flexiguard',
        producer: 'Chubb Broker',
        policyPeriod: '10-Oct-21 - 09-Oct-22',
        transactionEffectiveDate: '10-Oct-21',
        premium: '1500000',
        currency: 'SGD',
        lastUpdated: '10-Oct-21',
        actions: []
      },
      {
        typeId: 'New',
        quoteRefNo: 'QR0123456789',
        policyNo: 'P0123456789',
        status: 'in-progress',
        insuredName: 'Sodales ac',
        brokerage: 'Chubb Broker',
        productId: 'Flexiguard',
        producer: 'Chubb Broker',
        policyPeriod: '10-Oct-21 - 09-Oct-22',
        transactionEffectiveDate: '10-Oct-21',
        premium: '1500000',
        currency: 'SGD',
        lastUpdated: '10-Oct-21',
        actions: []
      },
      {
        typeId: 'New',
        quoteRefNo: 'QR0123456789',
        policyNo: 'P0123456789',
        status: 'unsuccessful',
        insuredName: 'Sodales ac',
        brokerage: 'Chubb Broker',
        productId: 'Flexiguard',
        producer: 'Chubb Broker',
        policyPeriod: '10-Oct-21 - 09-Oct-22',
        transactionEffectiveDate: '10-Oct-21',
        premium: '1500000',
        currency: 'SGD',
        lastUpdated: '10-Oct-21',
        actions: []
      },
      {
        typeId: 'New',
        quoteRefNo: 'QR0123456789',
        policyNo: 'P0123456789',
        status: 'under-review',
        insuredName: 'Sodales ac',
        brokerage: 'Chubb Broker',
        productId: 'Flexiguard',
        producer: 'Chubb Broker',
        policyPeriod: '10-Oct-21 - 09-Oct-22',
        transactionEffectiveDate: '10-Oct-21',
        premium: '1500000',
        currency: 'SGD',
        lastUpdated: '10-Oct-21',
        actions: []
      },
      {
        typeId: 'New',
        quoteRefNo: 'QR0123456789',
        policyNo: 'P0123456789',
        status: 'referral-pending-info',
        insuredName: 'Sodales ac',
        brokerage: 'Chubb Broker',
        productId: 'Flexiguard',
        producer: 'Chubb Broker',
        policyPeriod: '10-Oct-21 - 09-Oct-22',
        transactionEffectiveDate: '10-Oct-21',
        premium: '1500000',
        currency: 'SGD',
        lastUpdated: '10-Oct-21',
        actions: []
      },
    ]